# Generated by Django 5.2.5 on 2025-08-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='brandname',
        ),
    ]
