# Generated by Django 5.2.5 on 2025-08-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_inventory_brand_rename_brand_brand_brandname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brands',
        ),
    ]
