# Generated by Django 5.2.5 on 2025-08-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_brand_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='brandname',
            new_name='brand',
        ),
    ]
